n =input('Digite algo: ')
print(n, 'É composto por letras ou numeros?')
print(n.isalnum())
print(n, 'É composto por letras maiúsculas?')
print(n.isupper())
print(n, 'É composto por letras minúsculas?')
print(n.islower())
print(n, 'É composto por letras?')
print(n.isalpha())
print(n, 'É composto por números?')
print(n.isnumeric())
