nome = str(input('Digite seu nome completo: '))
print('Analisando seu nome...')
print('Seu nome em letras maiúsculas é: {} '.format(nome.upper()))
print('Seu nome em letras minúsculas é: {} '.format(nome.lower()))
lista = nome.split()
print('Quantidade de letras que o nome possui: {} '.format(len(''.join(lista))))
separa = nome.split()
print('Seu primeiro nome é {} e tem {} letras. '.format(separa[0], len(separa[0])))